image: registry.gitlab.com/metalibm-dev/metalibm/image:ci_image

before_script:

unit_tests:
  script:
    - export LD_LIBRARY_PATH=/app/local/lib/
    - export PYTHONPATH=/app/local/python/lib/python
    - PYTHONPATH=$PWD:$PYTHONPATH ML_SRC_DIR=$PWD python2.7 valid/unit_test.py --debug

non_regression:
  script:
    - export LD_LIBRARY_PATH=/app/local/lib/
    - export PYTHONPATH=/app/local/python/lib/python
    - PYTHONPATH=$PWD:$PYTHONPATH  ML_SRC_DIR=$PWD python2.7 valid/non_regression.py --debug

